# Generated by Django 3.1.5 on 2021-06-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='cat',
            new_name='category',
        ),
    ]
