# Generated by Django 3.1.5 on 2021-07-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210720_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
